FROM 31z4/tox:latest as base

# switch back to to allow using /.cache
USER root

RUN mkdir ${HOME}/.cache; \
    chown tox:tox ${HOME}/.cache; \
    mkdir ${HOME}/.local; \
    chown tox:tox ${HOME}/.local


USER tox
